### ISSUE TITLE
bogus maven metadata in newly published maven artifacts for org.eclipse.equinox.preference

### ISSUE THREAD

**Issue by cdietrich** [eclipse-platform/eclipse.platform.releng#47] opened 2022-06-15 04:07 UTC
https://search.maven.org/artifact/org.eclipse.platform/org.eclipse.equinox.preferences/3.10.0/jar

has

```
    <dependency>
      <groupId>org.osgi.service</groupId>
      <artifactId>org.osgi.service.prefs</artifactId>
      <version>[1.1.0,1.2.0)</version>
    </dependency>
```
which does not exist
as the group id is org.osgi

https://search.maven.org/artifact/org.osgi/org.osgi.service.prefs/1.1.2/jar

**Comment by akurtakov** [comment] 2022-06-15 05:27
Duplicate of https://github.com/eclipse-equinox/equinox.bundles/issues/54

**Closed by akurtakov** 2022-06-15 05:27 UTC

**Comment by cdietrich** [comment] 2022-06-15 05:38
@akurtakov is there on overview of all former eclipse github repos and orgs that helps to pick the correct place to search for existing issues?

**Comment by akurtakov** [comment] 2022-06-15 05:42
Basically there are 4 orgs and one can look in their issues:
* https://github.com/issues?user=eclipse-platform
* https://github.com/issues?user=eclipse-equinox
* https://github.com/issues?user=eclipse-jdt
* https://github.com/issues?user=eclipse-pde

These links provide issues from all repos in the given github org.

**Comment by HannesWell** [comment] 2022-06-15 06:40
Maybe it is worth to mention the list as well as the other Eclipse-TLPs in the Read-me of https://github.com/eclipse-platform/ ?

**Comment by akurtakov** [comment] 2022-06-15 06:47
I wouldn't be very thankful if you do that.
